### ISSUE TITLE
Attempted to load class "WeekAdvice" from namespace "PrestaShop\Module\AddonsConnect". Did you forget a "use" statement for another namespace?

### ISSUE THREAD

**Issue by DayBr3ak** [PrestaShop/docker#166]
Hello

A somewhat simple execution with PS_INSTALL_AUTO won't work out of the box when I go to the admin panel

Here is what I use:

`docker run -ti --name mysql --network prestashop-net -e MYSQL_ROOT_PASSWORD=admin -d mysql:5.7`

```docker run -ti --name prestashop --network prestashop-net -e DB_SERVER=mysql -e PS_INSTALL_AUTO=1 -e PS_ERASE_DB=1 -e PS_DEV_MODE=1 -e PS_DOMAIN=localhost:9080 -e PS_FOLDER_ADMIN=adminxkc -e PS_FOLDER_INSTALL=instalxxx -e PS_DEMO_MODE=1 -p 8080:80 -d prestashop/prestashop:1.7```

I want to then get to the admin panel so I open http://localhost:9080/adminxkc and I login with the default admin account

First I get:  Constant _PS_MODE_DEMO_ already defined in /var/www/html/config/defines.inc.php on line 43

But that's Ok I remove PS_DEMO_MODE and I get the following error:

Attempted to load class "WeekAdvice" from namespace "PrestaShop\Module\AddonsConnect".
Did you forget a "use" statement for another namespace?

Not sure why I can't run prestashop 1.7 as a simple demo, any advice? Or a weekadvice?

**Comment by Quetzacoalt91** [comment]
Hi,

That's a temporary issue with a module which has just been updated.
Thanks for letting us know by the way. We removed this version and currently replace it with the proper version.

Regards

**Comment by arafatx** [comment]
Sorry for disturbing a closed issue. Searching google about this error and this is the only result coming from the search engine. Is there an update for this? This still happens in prestashop 1.7.6.

**Comment by Quetzacoalt91** [comment]
The issue was fixed a few minutes after my last message.

If it happens again, this means you downloaded the module without its dependencies. If you know how [Composer](https://getcomposer.org/) works, you can get them by yourself, otherwise I recommend you to remove the module and download it again from the marketplace.

**Comment by arafatx** [comment]
Hai, it was the browser cache issue. Problem solved. Thanks a lot!

**Comment by Klemart3D** [comment]
I'm not using docker but I have this issue. I tried update composer + disable & remove cache + delete browser cahce + browsing in private mode, still the same.
This issue is only on AdminDashboard controller (= admin home page)
Error come from _psaddonsconnect_ module, do have we to delete it?

**Comment by gzlittle** [comment]
In the modules directory, move psaddonsconnect directory other name, As:
`mv psaddonsconnect_bak psaddonsconnect`
You can log in the admin controller.

**Comment by benftwc** [comment]
> In the modules directory, move psaddonsconnect directory other name, As:
> `mv psaddonsconnect psaddonsconnect_bak`
> You can log in the admin controller.

Kind of black esoteric magic, but works. Useful tip to fix
